### ISSUE TITLE
apache-mode package is currently broken

### ISSUE THREAD

**Issue by chillum** [milkypostman/melpa#2351]
It used to work okay, but now it's downloading and installing a file, that Emacs cannot parse as Emacs Lisp.

Don't know, where to look and what to fix (suggestions welcome), but at the moment `apache-mode` package is broken.

**Comment by purcell** [comment]
This is probably due to problems with the emacswiki, though I'm not sure why that would break our package: following changes made for the related issue #2294, error pages served by the wiki should not get turned into packages.

See also #2128.

**Comment by purcell** [comment]
P.S. I've just built this locally and it works fine, so there's a good chance that in a few hours time this problem will resolve itself.

**Comment by purcell** [comment]
The file being served up appears to be gzipped data according to `file(1)`, but is corrupt. It's most likely due to bad data from the wiki servers.

Aside: hey @milkypostman, the .el files like http://melpa.org/packages/apache-mode-20140625.1556.el are getting served with the content type `application/octet-stream` -- we should probably mark them as `text/plain`, right?

**Comment by purcell** [comment]
(Content type tweaked in 393799b)

**Comment by milkypostman** [comment]
This is not on our end. There is a problem with the elisp area on EmacsWiki currently.

**Comment by nicferrier** [comment]
Some files seem to have been erroneously cached. The cache lasts few a day currently. So it should be fine after a while. If the problem persists let us know via the wiki news page?

**Comment by chillum** [comment]
Now the `apache-mode` installs correctly. Thanks everybody.
