### ISSUE TITLE
python-mode recipe build not updating?

### ISSUE THREAD

**Issue by dfdeshom** [milkypostman/melpa#2486]
Hello,
The current version of python-mode has not been updated since 01/17/2015: http://melpa.org/#/python-mode . Since then, there have been several updates to the repository, which can be seen here: http://bazaar.launchpad.net/~python-mode-devs/python-mode/python-mode/changes . Any reasons the recipe is not being updated? I ask because python-mode version 20150117.955 has a bug which makes using python-mode unusable. This bug was fixed on 01/31 on the bzr repo, but I have not seen the changes reflected on melpa yet.

**Comment by purcell** [comment]
`bzr` was reporting uncommitted changes in our working copy, but it wasn't due to anything MELPA does: somehow the upstream repo must have got out of sync with the working copy. Perhaps there was a reorganisation of the repo upstream? No idea. In any case, I've removed our local copy, so this should fix itself during the next build cycle.
