### ISSUE TITLE
Is there a way to add external (non-elpa) dependencies?

### ISSUE THREAD

**Issue by cpitclaudel** [milkypostman/melpa#2538]
I'm writing a company-mode backend for Coq proof scripts. This requires ProofGeneral, a major mode for Emacs that is not currently distributed on melpa (in fact, their repo uses CVS).

I've created the relevant recipe, and it works perfectly when Proof General is available, but it fails if it is not. Is there a way to specify that dependency. Or should I make it so that my package installs successfully in all cases, but if proof-general fails to load then I show an error message when one tries to actually use my package?

Thanks.

**Comment by purcell** [comment]
MELPA supports CVS, so Proof General could potentially be added. I haven't looked, but it may require minor changes in order to be suitable for packaging.

Otherwise, the best solution (while not perfect) is to not declare a package dependency, and `(require ...)` Proof General in your code, so that it results in a load-time error for the user.

Hope that helps!

**Comment by cpitclaudel** [comment]
Thanks! Adding proof-general could be a nice idea. I was concerned about `(require ...)` raising an error at compilation time, forcing user to uninstall/reinstall the package. I'll wrap the relevant require in a check, and issue an error message.
