### ISSUE TITLE
The following packages are in melpa but not melpa stable

### ISSUE THREAD

**Issue by ruiyang** [milkypostman/melpa#2565]
Recently forked steve purcell's emacs.d. I didn't like to install packages from master, and prefer to install from melpa stable. However I found the following packages are not in stable repository. It would be nice to have them in melpa stable, so I won't need to install manually in the future. Also it makes updating easier.
Packages:
- cljsbuild
- css-eldoc
- csv-nav
- darcsum
- dired+
- wgrep
- fullframe
- git-blame
- highlight-escape-sequences
- highlight-symbol
- ipretty
- lively
- mwe-log-commands
- org-fstree
- org-mac-link
- project-local-variables
- redshank
- revive
- robe
- scratch
- sql-indent
- tidy
- vc-darcs

**Comment by ruiyang** [comment]
I know it is a long list. If the fix is to contact authors and ask them to add a version tag. I could share some of the work. Just let me know the parts that I can help.

Thanks,
Rui

**Comment by purcell** [comment]
This is really part of #1955, so I'll close this issues: the list above is only a very partial list.

Of course, if any of the packages on your list are from git repos, you can certainly feel free to contact the upstream authors and request that they add version tags.

A caution, though: if your goal is to have more reliable packages than those in MELPA, I'm not sure that MELPA Stable will really give that to you, and you might just be wasting your time. I've been using MELPA with my config for a couple of years now, and haven't experienced any major breakage.

A better solution might be to make periodic snapshots of packages which are working for you, or to be very selective about what you upgrade.

In any case, my config always targets the latest MELPA packages, since those are what I use.

-Steve
