### ISSUE TITLE
Single packages inf pkg files

### ISSUE THREAD

**Issue by lxsameer** [milkypostman/melpa#2658]
Is there any specific reason for not extracting `pkg-info` from `*-pkg.el` file for single packages ?

/ CC @milkypostman @purcell

**Comment by lxsameer** [comment]
I know that this behavior is not the convention for creating Emacs packages. But I think it doesn't hurt any one to do so.

For example since `package-build` does not provide any way other solution for extracting dependency data from a single package, except of putting dependencies in the header section of package source code. A tool like `cask` can't manage dependencies for a single package.

As you already knows `cask` holds the dependencies information in a separate file. So it can't pass dependencies to the `package-build` to put them in the built package.

I can think of two solution for this.
 **1)** before creating a single package lookup `pkg.el` file to extract `pkg-info` data ( I know, this is not conventional but can be handy ) .  
 **2)** Passing dependencies directly to `package-build`. I know you don't like it. but it's a solution.

Also I hacked the code a little bit. It seems that even I provide dependencies data in `pkg-info` structure `package-build` does not put dependencies in the resulted single package. Weird right ?

What do you think ?

**Comment by purcell** [comment]
If you provide `foo-pkg.el` and `foo.el` to `package-build`, then the package info *will* be taken from `foo-pkg.el`, and a `tar` package will be created containing both files. So that works okay, but it is obviously neater and generally preferred to distribute single-file packages as a single file.

Does that answer the question?

P.S. Using `cask`'s `package-file` directive, cask will read all the dependency information from the given `.el` file rather than relying on the `depends-on` forms in `Cask`. That generally reduces duplication, and is the preferred method for handling single-file packages.

**Comment by lxsameer** [comment]
@purcell So I think the mistake of mine it to pass `foo.el` as `files` parameters to `package-build-package` function. The right thing to do is to include the `foo-pkg.el` too . right ?

Also yeah you're right about `package-file`.

**Comment by purcell** [comment]
> @purcell So I think the mistake of mine it to pass foo.el as files parameters to package-build-package function. The right thing to do is to include the foo-pkg.el too . right ?

Yep, exactly. In fact, the default file spec includes `*.el`.

**Comment by lxsameer** [comment]
@purcell thanks
