### ISSUE TITLE
Gitlab package is broken.

### ISSUE THREAD

**Issue by marcinant** [milkypostman/melpa#2688]
Hi,

I would like to report that gitlab package doesn't work. Important parts of code are commented out and it's impossible to connect to server. Please remove this package, describe as experimental or contact with author.

**Comment by purcell** [comment]
Are you requesting that we remove the package instead of reporting the actual issues upstream? That seems backwards. :-)

We don't want broken packages, but the best way to resolve them is by working to get the upstream code fixed, and users are usually in a better position to do that than we MELPA maintainers are.

**Comment by marcinant** [comment]
I reported issue to upstream as well and some work is already done. My PR is just merged.

Sure it's better not to remove package. However if it's broken then it's very frustrating for users. So, if it's possible packages which are in fact 'work in progress' or 'experimental' should be marked properly not to confuse users.

Documentation is now updated and users can authorize to Gitlab hosts with private token.
There are some other bugs which I'll report and I hope to fix soon.

I'm closing this request and I hope this package is going to be fixed soon.

**Comment by purcell** [comment]
Great, thanks for working to fix this!

I can certainly understand that it's frustrating for users; there's a trade-off, because the more people use a broken package, the more likely it is to get fixed! If packages remain broken for an extended period of time, we're happy to remove them, but the best outcome is usually for the code to be fixed.
