### ISSUE TITLE
Q: What is the best way to resolve a package name conflict?

### ISSUE THREAD

**Issue by snosov1** [milkypostman/melpa#2690]
Hi!

My question is not strictly related to MELPA, but I need an advice on this, and I don't really know a better place to ask it. I hope, that you guys, can help me out.

So, I have this package on MELPA - [org-toc](http://melpa.org/#/org-toc). At some point, I recognized, that there's an older module with the exact same name in contrib org packages. And that some people that have both of them are facing conflicts. 

My understanding is that the issue is not very severe, since I got only 3 bug reports to date, and there's more than a 1000 of downloads of the package. But still, the whole situation is not very good, so I would like to fix it.

So, my question is - can you, please, suggest a good way to handle this?

Preferably, I would like to have a solution, that won't disturb the existing users, while providing a clean solution for new users and people who face the conflict and workaround it currently. 

Any help is much appreciated.

**Comment by purcell** [comment]
There's no perfect way to resolve this, but I'd suggest we rename the package. There's an `:old-names` key we can add to the recipe in MELPA, so that downloads will still be counted correctly, and the old package page will redirect to the new one. We can also tweet about the renaming when it happens.

But of course people who installed your `org-toc` package will not automatically find out that the package was renamed. Sooner or later they will find that it is not installable, and will probably look for it on your github or the MELPA package page, at which point they will find out what happened.

Really this is just a case of communicating as clearly as possible.
