### ISSUE TITLE
make the bookmark+ recipe available on melpa/stable

### ISSUE THREAD

**Issue by martintrojer** [milkypostman/melpa#2762]
Not sure if this is possible since this package is hosted on the emacs wiki.

Would be great if it was possible.

**Comment by purcell** [comment]
emacswiki packages are never in MELPA Stable, because there's no reliable way for them to indicate their version. The solution would normally be for the author to place the package under proper version control, but this is one of Drew's packages, and he will not do that.

Generally speaking, MELPA Stable will generally not work without MELPA for this reason: users are advised to explicitly install MELPA Stable versions of packages where desired, and to allow dependencies to be fulfilled from MELPA / GNU ELPA.

(There are various open issues related to this in the tracker, so I'll close this as redundant.)
