### ISSUE TITLE
add goto-chg-1.6 for evil in stable

### ISSUE THREAD

**Issue by transtone** [milkypostman/melpa#2813]
please

**Comment by milkypostman** [comment]
You have to contact the package maintainer and have them tag a 1.6 release.
Unfortunately we don't do manual versions. It's all based on version
control.

**Comment by purcell** [comment]
Problem is that goto-chg comes from the emacswiki, which is deliberately not supported by MELPA Stable. See related issues #1955, #2262 #2128, #2082.

**Comment by milkypostman** [comment]
I guess we need to contact the evil devs and see if they can either
integrate it into their package or convince the original author to move it
to vcs. I have never liked this dependency.

**Comment by jbyler** [comment]
So it looks like this is closed without a resolution.  Maybe evil should be removed from melpa-stable, since in its current state it can't be installed anyway?  Obviously I'd prefer that goto-chg and evil were both available, but not claiming to provide evil seems preferable to claiming to provide it when it doesn't actually work.

**Comment by milkypostman** [comment]
I think that despite the issue, people who install goto-chg manually may
still want to get evil stable updates from melpa-stable.

**Comment by egarrulo** [comment]
I have `goto-chg.el` version 1.6 in my `load-path`, but installing `evil` still raises the same error.  How should I install `goto-chg` manually to make installation work?  Thanks.
