### ISSUE TITLE
gh.el not on stable

### ISSUE THREAD

**Issue by rnkn** [milkypostman/melpa#2834]
Looks like everything is set up correctly for https://github.com/sigma/gh.el tagged releases to be on MELPA stable, but they don't appear to be coming through?

**Comment by milkypostman** [comment]
the problem is the submodule using ssh. `git@github.com:sigma/gh.el.git` in `.gitmodules`.

this is problematic for melpa because our bot doesn't have ssh public/private key it can't build this. I'm actually not sure how the `gh` recipe is actually building either.

if you could change it to use the https one that should work. Although it may require us manually reseting your working files which I am happy to do.

**Comment by sigma** [comment]
I fixed it in gh.el (it's the right thing to do anyway), but wouldn't it make sense for the bot to rewrite those URLs automatically?

Something like

    [url "https://github.com/"]
            insteadOf = git@github.com:

in its .gitconfig

**Comment by milkypostman** [comment]
Hrm maybe. That would probably be a good idea in general.

**Comment by purcell** [comment]
Or maybe to fail more noisily: we could unset `SSH_AUTH_SOCK` while building, so that authors can't build a package if it uses ssh-dependent submodule URLs, which they should notice during testing.

**Comment by milkypostman** [comment]
ok, so this will build on the next run. I basically wiped all the working directories on the server (which I like to do every now and again to reset everything a little bit) and so after the next full run completes you should see this package.

best,
d
