### ISSUE TITLE
convert description to html in package detail page

### ISSUE THREAD

**Issue by ChillarAnand** [milkypostman/melpa#2883]
looks like most package's readme file's are using markdown. reading this in melpa package details page under description section is annoying. 

markdown can be converted to html using `pandoc` or `python-markdown2` and then use it package description?

**Comment by purcell** [comment]
Descriptions on MELPA don't come from README files, but instead come from the `Commentary:` sections of `.el` files, in which Markdown is invalid: Emacs has its own markup which should be used there. *Some* people use Markdown there anyway, presumably so that they can generate their own `README.md` from the content, or because they wrongly assume that Markdown is supported by MELPA.

I don't think we're going to add Markdown support, so if you see raw markdown on MELPA package pages, it might be helpful to file a bug with the corresponding package authors so that they can fix it.
