### ISSUE TITLE
Questions about names of packages

### ISSUE THREAD

**Issue by mrkkrp** [milkypostman/melpa#2943]
Because of missing name spaces in Emacs Lisp we need to prefix everything with name of package. @purcell, makes sure that everyone follows the rules, and I think he does great work and that's how we should organize collection of Emacs packages that can live together. However short names are automatically get more valuable in this system. I want you to state clearly how long name of package can be. I'm sure that it's not a good idea to propose something named `m` without really good reason. How about two-letter package names? Are they allowed?

Another thing that makes me cautious is that some packages are "too cool for school", like `multiple-cursors`, which prefixes everything with `mc`. What if another package is created named exactly `mc` (hypothetical situation). Theoretically they should not conflict because they are different packages, but in practice `multiple-cursors` doesn't follow the rules, so everything is possible. Thus system of naming is already broken because rules are not the same for everyone.

Are you OK with this situation or can we do something about it?

I think acceptable names of packages should start with 3 letters, is it so?

**Comment by purcell** [comment]
Yep, it's too late to fix `multiple-cursors`'s `mc` prefix, but if that were submitted to MELPA today, I'd be working to get it fixed.

3 chars is probably a reasonable minimum length for package names, but even then I'd discourage such short names because a 3-char name is unlikely to be descriptive. (Well known acronyms might be okay, I suppose.) Authors think they're being clever when they invent short package names, but it's better for them in the long term if people can quickly understand what their package is for, and descriptive names help with that.

I'm not going to go as far as trying to set out rules for what is or is not acceptable for the elisp community as a whole, because I don't represent everyone -- my main goal here is to help people understand their choices and options, and to help them understand the benefit of following established community standards.
