### ISSUE TITLE
Can we have more prominent stable versions, please?

### ISSUE THREAD

**Issue by nschum** [milkypostman/melpa#3023]
I don't use melpa, but a few of my packages are on it.

[A recent issue](https://github.com/nschum/highlight-symbol.el/issues/35) caused some trouble, leading to requests to revert the work in progress. I was surprised by the number of users and subsequently found out it's because melpa promotes the bleeding edge of packages. (quote: "Well, this package is in MELPA, and many people expect things to work.")

I know that melpa-stable exists, but it seems like an afterthought. (It literally is the last entry in the README.) Why isn't it the default like in most package managers? Or why doesn't melpa offer both stable and snapshot versions? Or at least a warning about using unreleased and unsupported code.

I'm somewhat uncomfortable with the idea that a *majority* of users, by default, start using every small change immediately. Continuous Delivery is awesome, but not when it's pushed on a project not equipped for it. On small projects, it's sometimes weeks before I have time to even read issues. Fear of breaking something on a large scale is only going to discourage me from squeezing some work in. :)

So I do releases, because that's what I test reasonably and have some confidence in.

Now, I know I could just stop doing things in `master`, but that would impede people who really do want to try out unfinished things. A few brave early testers are important for making releases stable after all. :)

Sorry for all the ranting :wink:, I think melpa is great for getting code to users. :+1:  But maybe we can find a way to better communicate the package author's intent to users?

**Comment by mrkkrp** [comment]
I shouldn't have asked to revert the changes, I'm sorry about that. Although @tarsius is right that we should accept possibility of broken packages, people install packages to actually use them, and sometimes when they need to use them, but they are broken. It's OK if maintainers are willing to fix issues more or less quickly, imho.

If some package is in state when it's *completely* unusable for prolonged period of time, this is kind of situation that should be avoided by maintainers. Of course since @nschum didn't even know that his packages are on MELPA we cannot blame him in any case.

**Comment by purcell** [comment]
There's a trade-off here: most stuff doesn't break very often, and the MELPA snapshot mechanism at least ensures that when it's fixed, updated packages are available quickly. We try to be clear that MELPA is a snapshot archive, and that things may break from time to time. When breakage happens, at least MELPA ensures that the author will get prompt feedback. ;-)

MELPA Stable is not well supported, has relatively poor package coverage and (afaict) not widely used, not least because it's often not viable to use it without also using MELPA!

Neither @milkypostman nor myself use MELPA Stable, and there are various significant issues with it, all of which you can read about in the issue tracker if you're bored. :-) So that's why we don't promote it much - MELPA is generally a better experience for the typical user. Updated packages (broken or not) can always break a user's config anyway, and the lack of package version pinning in `package.el` is as much of a problem as MELPA's bleeding edge packages IMO -- when users don't have a mechanism to control which updates to take, they have no way to maintain a known-good config.

So the short answer is that more stable versions may or may not become available depending on whether anyone steps up to overcome the various related issues and make it happen.

I'll close this issue because I think it's covered by other open issues here, but feel free to discuss further here.
