### ISSUE TITLE
Memento is not found. 

### ISSUE THREAD

**Issue by ReneFroger** [milkypostman/melpa#3039]
When I'm trying to install the package memento. I get the following message: 

       http://melpa.org/packages/memento-20150819.849.el: Not found. 

I'm trying to figure out what went wrong here. The repository of Memento is still available.

**Comment by xuchunyang** [comment]
melpa doesn't keep old packages., http://melpa.org/#/memento says "memento 20150822.334", so your melpa archive is outdated, you have to update that (e.g., with `M-x package-refresh-contents`) before installing memento. (You can also use `M-x list-packages` to enter Package Menu to install package, then you won't have this issue since refreshing will be done automatically every time.)

**Comment by ReneFroger** [comment]
Chunyang, thanks for your helpful answer. Now I get it. Thanks for the tip.
