### ISSUE TITLE
An idea for easier MELPA maintainabiliy

### ISSUE THREAD

**Issue by steckerhalter** [milkypostman/melpa#3088]
We discussed this for quelpa once (see https://github.com/quelpa/quelpa/blob/master/world-domination.org where @wasamasa wrote down some of the rationale).

So in the case of MELPA if an author wants to support MELPA he could put a `Melpafile` into the root of his project containing the recipe to build the package.

So you would have authors/maintainers control the build options and necessary changes could be made by themselves without the need for a PR.

On MELPA you would just have to register the URL and not bother with the details or changes of the recipe and so on.

**Comment by vyp** [comment]
+1

Off topic, but this would be nice for quelpa too, since quelpa can just look for the `Melpafile` and use it if no recipe was given (i.e. `(quelpa '<package-name>)`). (Then fallback to searching Melpa for an appropriate recipe if no `Melpafile`.)

**Comment by purcell** [comment]
This is of course a possibility, and perhaps `Packagefile` would event be better than `Melpafile`, but one obvious problem I see is that many repositories host multiple packages in the same directory.

Also, I'd be concerned that package authors would often change their recipes in ways which would break packages, or to mess them up from MELPA's perspective (e.g. by specifying fixed or stale tags/commits/branches). The current scheme prevents this and also allows conversations between the authors and MELPA maintainers which I think benefit both sides.

(PS. I don't really agree with the claim in the document you linked to that MELPA chokes on > 2000 packages. There's no reason we couldn't scale to tens of thousands with a little work -- the model seems perfectly sustainable to me.)

**Comment by steckerhalter** [comment]
> This is of course a possibility, and perhaps Packagefile would event be better than Melpafile, but one obvious problem I see is that many repositories host multiple packages in the same directory.

ok, I guess that could be handled by making the `Packagefile` format so that it can deal with these cases as well

> Also, I'd be concerned that package authors would often change their recipes in ways which would break packages, or to mess them up from MELPA's perspective (e.g. by specifying fixed or stale tags/commits/branches). The current scheme prevents this and also allows conversations between the authors and MELPA maintainers which I think benefit both sides.

That's certainly possible as this would make author/maintainers responsible. So if they break the recipe the bug would be filed on their issue tracker instead of MELPA and if an author/maintainer does not do anything about it you would find out if a project is not maintained anymore and refrain from using their `Packagefile`

> (PS. I don't really agree with the claim in the document you linked to that MELPA chokes on > 2000 packages. There's no reason we couldn't scale to tens of thousands with a little work -- the model seems perfectly sustainable to me.)

I don't really know, the argument is not mine. I don't think this is important in this whole matter.

**Comment by vyp** [comment]
> Also, I'd be concerned that package authors would often change their recipes in ways which would break packages, or to mess them up from MELPA's perspective

Is there anyway a recipe could be considered malicious to MELPA? And I assume Melpa just ignores incorrect recipes or recipes that fail to build? And does it automatically attempt to rebuild a failed build after some time, or does it just stop trying to bulid the package all together?

Because if not (to the first question), I think the convenience is worth it. However, if Melpa stops attempting to build failing packages, this could end with more work for you because then package maintainers will come here asking what went wrong, whereas with the current system, you'd already have known about the potential issue and probably even prevented it in the first place, saving a lot of time and effort.

That would be the case if melpa *does not* stop attempting to build failing packages, but at least in this case the fix can be done upstream, with you just providing guidance.

For repositories that host multiple packages, I guess a `Packagefile` would just simply not be an option.

**Comment by steckerhalter** [comment]
Btw, you can close the issue any time you like as it is just an idea you might like or not.

**Comment by milkypostman** [comment]
this is exactly something we were trying to avoid with melpa. when this all started I was frustrated with the state of marmalade because package maintainers didnt do the legwork to keep their package up to date. and even with a file in the repo i think this is still the case. except for 10% of the very intricate packages where the maintainers write unit tests and actually care for their packages,the 90% barely gets their code committed. and this has to be all or nothing, because if its optional then we would basically have to keep maintaining our recipes, but would also have to support recipes we don't own.

the benefit of melpa is that we empower *us* or the community to support the burden of packaging, taking that away from the package maintainers. if I want a package in MELPA then *I*  can motivate myself to get it in MELPA and it will happen, otherwise i need to go through the author who may not have any interest in this.

**Comment by steckerhalter** [comment]
Sounds reasonable, I'm closing this then. Thanks for taking the time to discuss it.
