### ISSUE TITLE
Melpa stable picks the wrong tag for use-package

### ISSUE THREAD

**Issue by lvillani** [milkypostman/melpa#3180]
For some reason Melpa Stable picks up an older tag called `20140601` for the `use-package` project, instead of picking up the `2.1` tag corresponding to latest stable version.

It seems that the issue stems from the fact that either `package.el` or Melpa splits the version strings around periods and ends up comparing `20140601` with `2`. I am not sure if the problem lies in `use-package` or Melpa. I believe that Melpa should give less priority to tags that resemble an ISO8601 date.

One quick work around would be to remove the `20140601` tag, but I'm not sure if it's doable since someone, somewhere might depend on that to be available.

**Comment by vyp** [comment]
Ref https://github.com/jwiegley/use-package/issues/249.

**Comment by milkypostman** [comment]
Do tags have metadata about when they were created? How do we know the most
recent tag?

**Comment by purcell** [comment]
We use the latest numeric tag, with or without a `v` prefix. It's hard to argue that's unreasonable, and adding special handling for versions which look like a date would probably just break other repos. (There are no timestamps for tags, but that's immaterial because it's perfectly reasonable to add version tags today for historical releases which were never originally tagged.)

**Comment by lvillani** [comment]
This should be fixed now. Closing.
