### ISSUE TITLE
Force package update

### ISSUE THREAD

**Issue by arthurnn** [milkypostman/melpa#3181]
In the README it is stated:

> Packages are updated at intervals throughout the day.

How/where that process happen? Can you point me to the file? I am wondering how frequently they run, is that a cron task or something?
I am asking those question, because I would like to know if, with the current architecture, we can do some action to force a new fetch of the package. So if I update a package, I can hit a button or something to invalidate to cache.

Let me know.. thanks

**Comment by milkypostman** [comment]
There was recently another issue on this which I cannot recall offhand.
Please have a look in the closed issues for more info.

If you look in the scripts directory you can see the actual process we run
to build all packages. This script runs then takes a short break, an hour I
believe, then does it all again. I think we build packages roughly every
two hours but with growth that may have changed.

We don't want to build a hook type mechanism because that is additional
infrastructure to maintain and is only valuable in some use cases.

Is there a particular problem you're having that you would need this? Are
we just not fast enough in updating?

**Comment by vyp** [comment]
I think @milkypostman might be referring to #3162.

**Comment by arthurnn** [comment]
I see, I will take a closer look into how the scripts work. My next question is, if I handle all the work on making a webhook work, and setup of small server, etc. Would you be interested in that? As far as I can tell I am not the only one interested in a "more live" update of the packages, we probably could do a small webhook service and have a big win in the end.
Thoughts?

**Comment by vyp** [comment]
I think it might not scale well? As in, there's currently about 2700 packages and it continues to grow every day of course... so I think a 'snapshot' system like it has currently is the way to go? Then again, 'building' emacs packages does not really take that long does it? So maybe this isn't really an issue.

> As far as I can tell I am not the only one interested in a "more live" update of the packages

I honestly don't think the majority of users care about having more live package versions, so a delay of a few hours or so between latest default branch commit and melpa version is quite acceptable I believe. So I agree with @purcell when he says: "It's hard to see that it would all be worth the effort really." (Unless this whole thing isn't really too much effort for you to do and maintain.)

Those who do care are probably users that are interested in testing out a recent commit (for a feature/bug fix) asap. For that I'd just recommend to them to use a tool like [quelpa](https://github.com/quelpa/quelpa) which is sort of made for that sort of scenario. If you're not familiar with quelpa, it's like el-get but for package.el, so it would install exactly like if you used melpa. I know it's not directly solving this issue, but maybe that's the sort of thing you were after? (So maybe it can help you from doing unnecessary work.)

**Comment by purcell** [comment]
Also don't forget that we'd still need to run a batch build anyway, because we couldn't rely on the webhooks all the time, so we'd have 2 code paths for building packages. I'd really rather find a single simple scheme with acceptable compromises. There's more we could do to parallelise our current build, for example, and to reduce the overall build cycle time.
