### ISSUE TITLE
alias for deleted package?

### ISSUE THREAD

**Issue by fommil** [milkypostman/melpa#3434]
there is currently a `scala-mode` and a `scala-mode2`.

Nobody uses `scala-mode`, but we'd like to start using it and then make `scala-mode2` simply be an alias to it so that everybody who depends on `scala-mode2` would simply get upgraded automatically. Is that possible?

**Comment by milkypostman** [comment]
it's not currently possible with the current package management system. and unfortunately I think it might be hard to actually do once you rename. because the files in the package need to match the name of the package in some way at least.

there are kinda two options,

1. just rename it, notify people, and eventually it'll sort itself out because people will see there is no `scala-mode2` anymore.

2. we could create both `scala-mode` and `scala-mode2` from the same repo as long as there was a `scala-mode-pkg.el` and a `scala-mode2-pkg.el` file in the repo. but this is tricky and really doesn't help anyone in the long run.

so if you want to make scala-mode2 the new scala-mode then that's fine but we would want to get @bradwright to sign-off on this because he added the original recipe.

**Comment by fommil** [comment]
ok thanks for the detailed response!

I guess what we could do is rename our files/packages to `scala-mode` and then issue a minimal `scala-mode2` which simply depends/requires `scala-mode`.

I suspect @bradwright wanted access to `scala-mode` at some point and uploaded the recipe. The sources are owned by @scala so if you're wanting sign-off from the authors of `scala-mode`, it is probably @adriaanm who is in the position to do that https://github.com/scala/scala-tool-support/tree/master/tool-support/emacs

**Comment by bradwright** [comment]
I'm okay with this - I don't even use the mode anymore myself. :+1:

**Comment by milkypostman** [comment]
sgtm @fommil that's fine, send a PR when you get a chance.

**Comment by fommil** [comment]
Will do!
