### ISSUE TITLE
Add ability to use MELPA website from eww (or any other textual browser)

### ISSUE THREAD

**Issue by dakrone** [milkypostman/melpa#3483]
I have all the links opened from Emacs going through `eww`, but unfortunately melpa.org doesn't display packages quite correctly due to javascript not being available:

For the URL: http://melpa.org/#/projectile-sift

Eww shows:

![screenshot from 2016-01-11 10-52-59](https://cloud.githubusercontent.com/assets/19060/12241681/bc2e9f3e-b851-11e5-8baf-43febfa302e6.png)

It would be great if I were able to read/browse/use melpa.org from Emacs via `eww`.

**Comment by purcell** [comment]
Thanks for filing this. I can appreciate that this use case is a little frustrating, but the MELPA website is a single-page app because that doesn't require any server-side software or pre-generation of pages. There is therefore no easy way to fix this, and I don't believe it is worth a bigger effort, so I'm going to go ahead and close this issue, sorry.
